version: '3'

services:
  db:
    image: postgres
    environment:
     - POSTGRES_PASSWORD=db
     - POSTGRES_USER=db
     - POSTGRES_DB=db
    expose:
     - 5432
    ports:
      - "5433:5432"
  web:
    restart: always
    build: .
    command: sh start.sh
    volumes:
      - .:/webapp
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=cherrysoft.org
      - LETSENCRYPT_HOST=cherrysoft.org
