# Generated by Django 3.0.4 on 2020-03-28 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('abbreviation', models.CharField(max_length=3)),
                ('bip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('abbreviation', models.CharField(max_length=5)),
                ('bip', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpapp.Country')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('abbreviation', models.CharField(max_length=10)),
                ('ownership', models.CharField(max_length=10)),
                ('n_students', models.IntegerField()),
                ('n_staff', models.IntegerField()),
                ('n_profs', models.IntegerField()),
                ('city', models.CharField(max_length=64)),
                ('budget', models.IntegerField()),
                ('corona_page', models.CharField(max_length=600)),
                ('main_page', models.CharField(max_length=12)),
                ('quality', models.CharField(max_length=12)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpapp.State')),
            ],
        ),
    ]
