# Generated by Django 3.0.4 on 2020-03-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpapp', '0004_auto_20200328_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='stock_price',
            field=models.FloatField(),
        ),
    ]
