# Generated by Django 3.0.4 on 2020-03-29 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpapp', '0005_auto_20200328_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Implemented',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.IntegerField()),
                ('date', models.DateField()),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpapp.University')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpapp.Measure')),
            ],
        ),
    ]
